# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

adapter: mysql2
database: development
pool: 20
host: 106.186.20.240
username: development
password: development
timeout: 60000

