# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

adapter: mysql2
database: crawldata
pool: 20
host: localhost
username: root
password: password
timeout: 60000

